---
apiVersion: v1
metadata:
  name: harbor
  namespace: nodejs-builds
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnb2hhcmJvci4xMC4wLjAuMTI3Lm5pcC5pbzozMDAwMyI6IHsKCQkJImF1dGgiOiAiWVdSdGFXNDZTR0Z5WW05eU1USXpORFU9IgoJCX0sCgkJImhhcmJvci4xMC4wLjAuMTI3Lm5pcC5pbzozMDAwMyI6IHsKCQkJImF1dGgiOiAiWVdSdGFXNDZTR0Z5WW05eU1USXpORFU9IgoJCX0sCgkJImh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxLyI6IHsKCQkJImF1dGgiOiAiYldGeWRHbHViRzkxY21SMWMzZGhiWGs2UzJGdVpHbHJkWEJ3WVcxQU1USXoiCgkJfQoJfQp9
kind: Secret
type: kubernetes.io/dockerconfigjson
---
apiVersion: batch/v1
kind: Job
metadata:
  name: nodejs-builds
  namespace: nodejs-builds
spec:
  backoffLimit: 4
  ttlSecondsAfterFinished: 300
  template:
    spec:
     imagePullSecrets:
     - name: "harbor"
     containers:
     - name: sidecar-nodejs
       image: "harbor.10.0.0.127.nip.io:30003/builds/sidecar-nodejs:1.0"
       imagePullPolicy: Always
       command:
       - /bin/bash
       - -c
       - cp /home/* /data
       volumeMounts:
       - name: builddata
         mountPath: /data
     - name: nodejs
        image: gcr.io/kaniko-project/executor:v1.6.0-debug
        env:
        - name: HARBOR_USERNAME
          valueFrom:
            secretKeyRef:
              name: nodejs-secrets
              key: harbor-username
        - name: HARBOR_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nodejs-secrets
              key: harbor-password
        command: ["/home/build-docker.sh"]
        volumeMounts:
        - name: builddata
          mountPath: /home
      restartPolicy: Never

      volumes:
      - name: builddata
        emptyDir:
          sizeLimit: 1G
