apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  namespace: nodejs-builds
spec:
  template:
    spec:
      containers:
      - name: sidecar-nodejs
        image: "alpine:latest"
        imagePullPolicy: Always
        command:
        - /bin/sh
        - -c
        - echo "{\\"auths\\":{\\"10.0.0.127:30003\\":{\\"username\\":\\"admin\\",\\"password\\":\\"Harbor12345\\"}}}" > /kaniko/.docker/config.json
        volumeMounts:
        - name: docker-cfg
          mountPath: /kaniko/.docker
      - name: alpine-harbor
        image: gcr.io/kaniko-project/executor:v1.6.0-debug
        command:
          - sleep 60
          - /kaniko/executor -f Dockerfile -c `pwd` --insecure --skip-tls-verify --destination=10.0.0.127:30003/packer/packer:latest
        volumeMounts:
        - name: docker-cfg
          mountPath: /kaniko/.docker
      restartPolicy: Never

      volumes:
      - name: docker-cfg
        emptyDir:
          sizeLimit: 1G
