apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  namespace: nodejs-builds
spec:
  template:
    spec:
      containers:
      - name: alpine-harbor
        image: gcr.io/kaniko-project/executor:v1.6.0-debug
        command:
          - echo "{\"auths\":{\"10.0.0.127:30003\":{\"username\":\"admin\",\"password\":\"Harbor12345\"}}}" > /kaniko/.docker/config.json
          - cat /kaniko/.docker/config.json
          - /kaniko/executor -f Dockerfile -c `pwd` --insecure --skip-tls-verify --destination=10.0.0.127:30003/packer/packer:latest
      restartPolicy: Never
