---
apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnb2hhcmJvci4xMC4wLjAuMTI3Lm5pcC5pbzozMDAwMyI6IHsKCQkJImF1dGgiOiAiWVdSdGFXNDZTR0Z5WW05eU1USXpORFU9IgoJCX0sCgkJImhhcmJvci4xMC4wLjAuMTI3Lm5pcC5pbzozMDAwMyI6IHsKCQkJImF1dGgiOiAiWVdSdGFXNDZTR0Z5WW05eU1USXpORFU9IgoJCX0sCgkJImh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxLyI6IHsKCQkJImF1dGgiOiAiYldGeWRHbHViRzkxY21SMWMzZGhiWGs2UzJGdVpHbHJkWEJ3WVcxQU1USXoiCgkJfQoJfQp9
kind: Secret
metadata:
  creationTimestamp: null
  name: harbor
type: kubernetes.io/dockerconfigjson
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      imagePullSecrets: 
      - name: "harbor"
      containers:
      - name: sidecar-nodejs
        image: "harbor.10.0.0.127.nip.io:30003/builds/nodejs:1.0"
        imagePullPolicy: Always
        command: 
        - cp /tmp/build-docker.sh /data/build-docker.sh
        - cp /tmp/nodejs-Dockerfile /data/nodejs-Dockerfile
        volumeMounts:
        - name: docker-cfg
          mountPath: /data
      - name: nodejs
        image: gcr.io/kaniko-project/executor:v1.6.0-debug
        command: ["/tmp/build-docker.sh"]
        volumeMounts:
        - name: docker-cfg
          mountPath: /tmp
      restartPolicy: Never

      volumes:
      - name: docker-cfg
        emptyDir:
          sizeLimit: 1G
